version: '3.3'
services:
  cohn-treemaker:
    image: sc-registry.fredhutch.org/cohn-treemaker:latest
    networks:
      - sc-swarm-net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cohn-treemaker.rule=Host(`koalafytrees.fredhutch.org`)"
        - "traefik.http.routers.cohn-treemaker-secured.rule=Host(`koalafytrees.fredhutch.org`)"
        - "traefik.http.routers.cohn-treemaker.entrypoints=web,web-secured"
        - "traefik.http.services.cohn-treemaker.loadbalancer.server.port=8501" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.cohn-treemaker.tls=true"

networks:
  sc-swarm-net:
    external: true